steps:
  - id: 'apply migrations'
    name: 'gcr.io/google-appengine/exec-wrapper'
    entrypoint: 'bash'
    args:
      [
        '-c',
        '/buildstep/execute.sh -i gcr.io/${PROJECT_ID}/${_SERVICE_NAME} -s $_CLOUDSQL_INSTANCE_FULL_NAME -e DATABASE_URL=$$DATABASE_URL -- yarn prisma migrate deploy',
      ]
    secretEnv: ['DATABASE_URL']
    dir: 'google-cloud-prisma-migrate'
timeout: 2000s
substitutions:
  _CLOUDSQL_INSTANCE_FULL_NAMEL: 'bizpark-dev:asia-northeast1:bizpark-db-staging'
  _ARTIFACT_REPOSITORY_IMAGE_NAME: 'Artifact Registry にあるイメージ名'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
    env: DATABASE_URL
