version: "3.8"
services:
  db:
    image: "postgres:14"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
    volumes:
      - "bizpark_db_data:/var/lib/postgresql/data"

volumes:
  bizpark_db_data:
