version: "3.8"
services:
  db:
    image: "postgres:14"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
    volumes:
      - "bizpark_db_data:/var/lib/postgresql/data"
    networks:
      - bizpark-dev

  serevr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    environment:
      NODE_ENV: dev
      GOOGLE_APPLICATION_CREDENTIALS: /google_credentials.json
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres?schema=public
    networks:
      - bizpark-dev
    volumes:
      - .:/app
      - /app/node_modules
      - ./cred.json:/google_credentials.json
      - ./schema.graphql:/app/schema.graphql
    ports:
      - 4000:4000
      - 5555:5555
    depends_on:
      - db

volumes:
  bizpark_db_data:
networks:
  bizpark-dev:
    driver: bridge
